[project]
name = "yths-sankey"
version = "0.1.0"
description = "Generates a Sankey diagram from given edges. Tries to minimize overlapping edges."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
